version: '3.8'

services:
  # Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hilabs_roster
      POSTGRES_USER: hilabs
      POSTGRES_PASSWORD: hilabs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hilabs -d hilabs_roster"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Message Queue
  mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: hilabs
      RABBITMQ_DEFAULT_PASS: hilabs_password
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Object Storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: hilabs
      MINIO_ROOT_PASSWORD: hilabs_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Email Testing
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  # API Server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.simple
    environment:
      - DATABASE_URL=postgresql://hilabs:hilabs_password@db:5432/hilabs_roster
      - RABBITMQ_URL=amqp://hilabs:hilabs_password@mq:5672//
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=hilabs
      - MINIO_SECRET_KEY=hilabs_password
      - MINIO_BUCKET=hilabs-artifacts
      - VLM_ENABLED=false
      - LOCAL_LLM_ENABLED=false
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Worker
  worker:
    build:
      context: ./api
      dockerfile: Dockerfile.simple
    environment:
      - DATABASE_URL=postgresql://hilabs:hilabs_password@db:5432/hilabs_roster
      - RABBITMQ_URL=amqp://hilabs:hilabs_password@mq:5672//
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=hilabs
      - MINIO_SECRET_KEY=hilabs_password
      - MINIO_BUCKET=hilabs-artifacts
      - VLM_ENABLED=false
      - LOCAL_LLM_ENABLED=false
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./api:/app
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  postgres_data:
  minio_data:
